name: Quality assurance

on:
  - push
  - workflow_dispatch

env:
  GO_VERSION: '1.22.2'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - name: Install C/C++ deps
        run: sudo apt install -y build-essential libgtk-3-dev
      - name: Check code style with golangci-lint
        uses: golangci/golangci-lint-action@v4
      - name: Check code style with revive
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          path: "./..."
      - name: Test
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          make test
